# Generated by Django 5.1.5 on 2025-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitstats", "0002_commit_stats_parsed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="commit_hash",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
