# Generated by Django 5.1.7 on 2025-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitstats", "0004_commitstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositorySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "gitstats_repository_source",
            },
        ),
    ]
