# Generated by Django 5.1.7 on 2025-04-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitstats", "0005_repositorysource"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gitstats.repositorysource",
            ),
        ),
    ]
