# Generated by Django 5.1.7 on 2025-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitstats", "0006_repository_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="gitlab_project_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
